version: '3'
services:
  frontend:
    build:
      context: ./vue-frontend
    ports:
      - "8080:8080"
    depends_on:
      - backend

  backend:
    build:
      context: ./flask-backend
    ports:
      - "5000:5000"
